# Generated by Django 5.1.2 on 2024-12-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0002_book_author_book_is_bestseller_alter_book_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
