# Generated by Django 5.1.2 on 2024-12-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0007_country_book_published_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(
                related_name="books", to="book_outlet.country"
            ),
        ),
    ]
