# Generated by Django 5.1.2 on 2024-12-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0008_alter_book_published_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(to="book_outlet.country"),
        ),
    ]
